"""Add matchmaking models

Revision ID: 04b2afee29fa
Revises: 335796f1502c
Create Date: 2026-05-04 13:00:12.958753
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04b2afee29fa'
down_revision: Union[str, None] = '335796f1502c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industry_relationships',
    sa.Column('industry_a_id', sa.UUID(), nullable=False),
    sa.Column('industry_b_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=30), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['industry_a_id'], ['industry_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['industry_b_id'], ['industry_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industry_relationships_id'), 'industry_relationships', ['id'], unique=False)
    op.create_index(op.f('ix_industry_relationships_industry_a_id'), 'industry_relationships', ['industry_a_id'], unique=False)
    op.create_index(op.f('ix_industry_relationships_industry_b_id'), 'industry_relationships', ['industry_b_id'], unique=False)
    op.create_table('match_suggestions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('matched_user_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('partnership_strategy', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('context', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['matched_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_suggestions_id'), 'match_suggestions', ['id'], unique=False)
    op.create_index(op.f('ix_match_suggestions_matched_user_id'), 'match_suggestions', ['matched_user_id'], unique=False)
    op.create_index(op.f('ix_match_suggestions_user_id'), 'match_suggestions', ['user_id'], unique=False)
    op.create_table('matching_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('business_description', sa.Text(), nullable=True),
    sa.Column('services_offered', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('looking_for', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_sectors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('matching_enabled', sa.Boolean(), nullable=False),
    sa.Column('matching_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matching_profiles_id'), 'matching_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_matching_profiles_user_id'), 'matching_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matching_profiles_user_id'), table_name='matching_profiles')
    op.drop_index(op.f('ix_matching_profiles_id'), table_name='matching_profiles')
    op.drop_table('matching_profiles')
    op.drop_index(op.f('ix_match_suggestions_user_id'), table_name='match_suggestions')
    op.drop_index(op.f('ix_match_suggestions_matched_user_id'), table_name='match_suggestions')
    op.drop_index(op.f('ix_match_suggestions_id'), table_name='match_suggestions')
    op.drop_table('match_suggestions')
    op.drop_index(op.f('ix_industry_relationships_industry_b_id'), table_name='industry_relationships')
    op.drop_index(op.f('ix_industry_relationships_industry_a_id'), table_name='industry_relationships')
    op.drop_index(op.f('ix_industry_relationships_id'), table_name='industry_relationships')
    op.drop_table('industry_relationships')
    # ### end Alembic commands ###
