"""add_redemption_tokens_and_coupon_codes

Revision ID: 15e5eca89ac6
Revises: b9de2f4fa83a
Create Date: 2026-04-06 16:23:40.211109
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15e5eca89ac6'
down_revision: Union[str, None] = 'b9de2f4fa83a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupon_codes',
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'USED', 'EXPIRED', name='coupon_status'), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offer_id', 'user_id', name='unique_coupon_per_user_offer')
    )
    op.create_index(op.f('ix_coupon_codes_code'), 'coupon_codes', ['code'], unique=True)
    op.create_index(op.f('ix_coupon_codes_id'), 'coupon_codes', ['id'], unique=False)
    op.create_index(op.f('ix_coupon_codes_offer_id'), 'coupon_codes', ['offer_id'], unique=False)
    op.create_index(op.f('ix_coupon_codes_user_id'), 'coupon_codes', ['user_id'], unique=False)
    op.create_table('redemption_tokens',
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'EXPIRED', 'CANCELLED', name='token_status'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signer_name', sa.String(length=255), nullable=True),
    sa.Column('signature_data', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redemption_tokens_id'), 'redemption_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_redemption_tokens_offer_id'), 'redemption_tokens', ['offer_id'], unique=False)
    op.create_index(op.f('ix_redemption_tokens_token'), 'redemption_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_redemption_tokens_user_id'), 'redemption_tokens', ['user_id'], unique=False)
    op.add_column('offer_redemptions', sa.Column('redemption_token_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'offer_redemptions', 'redemption_tokens', ['redemption_token_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offer_redemptions', type_='foreignkey')
    op.drop_column('offer_redemptions', 'redemption_token_id')
    op.drop_index(op.f('ix_redemption_tokens_user_id'), table_name='redemption_tokens')
    op.drop_index(op.f('ix_redemption_tokens_token'), table_name='redemption_tokens')
    op.drop_index(op.f('ix_redemption_tokens_offer_id'), table_name='redemption_tokens')
    op.drop_index(op.f('ix_redemption_tokens_id'), table_name='redemption_tokens')
    op.drop_table('redemption_tokens')
    op.drop_index(op.f('ix_coupon_codes_user_id'), table_name='coupon_codes')
    op.drop_index(op.f('ix_coupon_codes_offer_id'), table_name='coupon_codes')
    op.drop_index(op.f('ix_coupon_codes_id'), table_name='coupon_codes')
    op.drop_index(op.f('ix_coupon_codes_code'), table_name='coupon_codes')
    op.drop_table('coupon_codes')
    # ### end Alembic commands ###
