"""add_two_factor_enabled_to_users

Revision ID: 260be11477f8
Revises: c4e1a8d97f02
Create Date: 2026-05-19 13:26:50.191736
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '260be11477f8'
down_revision: Union[str, None] = 'c4e1a8d97f02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('two_factor_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'two_factor_enabled')
    # ### end Alembic commands ###
