"""add_two_factor_enabled_to_users

Revision ID: 260be11477f8
Revises: c4e1a8d97f02
Create Date: 2026-05-19 13:26:50.191736
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '260be11477f8'
down_revision: Union[str, None] = 'c4e1a8d97f02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marketplace_listings', 'is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint('privilege_cards_nfc_uid_key', 'privilege_cards', type_='unique')
    op.drop_index('ix_privilege_cards_nfc_uid', table_name='privilege_cards')
    op.create_index(op.f('ix_privilege_cards_nfc_uid'), 'privilege_cards', ['nfc_uid'], unique=True)
    op.add_column('users', sa.Column('two_factor_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'two_factor_enabled')
    op.drop_index(op.f('ix_privilege_cards_nfc_uid'), table_name='privilege_cards')
    op.create_index('ix_privilege_cards_nfc_uid', 'privilege_cards', ['nfc_uid'], unique=False)
    op.create_unique_constraint('privilege_cards_nfc_uid_key', 'privilege_cards', ['nfc_uid'])
    op.alter_column('marketplace_listings', 'is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
