"""add_marketplace_roi_fields

Revision ID: 335796f1502c
Revises: e870291fa9b9
Create Date: 2026-04-30 17:01:11.064599
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '335796f1502c'
down_revision: Union[str, None] = 'e870291fa9b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE intereststatus AS ENUM ('PENDING', 'DEAL_CONFIRMED', 'CANCELLED')")
    op.add_column('marketplace_interests', sa.Column('status', sa.Enum('PENDING', 'DEAL_CONFIRMED', 'CANCELLED', name='intereststatus'), nullable=False))
    op.add_column('marketplace_interests', sa.Column('business_value', sa.Numeric(precision=15, scale=2), nullable=True))
    op.create_index(op.f('ix_marketplace_interests_status'), 'marketplace_interests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketplace_interests_status'), table_name='marketplace_interests')
    op.drop_column('marketplace_interests', 'business_value')
    op.drop_column('marketplace_interests', 'status')
    op.execute("DROP TYPE intereststatus")
    # ### end Alembic commands ###
