"""add_card_history_table

Revision ID: 3a409dd0fa33
Revises: 8a9b2c3d4e5f
Create Date: 2026-05-12 09:20:58.231001
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a409dd0fa33'
down_revision: Union[str, None] = '8a9b2c3d4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_history',
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_card_number', sa.String(length=50), nullable=True),
    sa.Column('new_card_number', sa.String(length=50), nullable=True),
    sa.Column('old_nfc_uid', sa.String(length=100), nullable=True),
    sa.Column('new_nfc_uid', sa.String(length=100), nullable=True),
    sa.Column('old_version', sa.Integer(), nullable=True),
    sa.Column('new_version', sa.Integer(), nullable=True),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['privilege_cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_history_card_id'), 'card_history', ['card_id'], unique=False)
    op.create_index(op.f('ix_card_history_id'), 'card_history', ['id'], unique=False)
    op.create_index(op.f('ix_card_history_user_id'), 'card_history', ['user_id'], unique=False)
    op.alter_column('marketplace_listings', 'is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('privilege_cards', sa.Column('card_version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('privilege_cards', sa.Column('nfc_uid', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_privilege_cards_nfc_uid'), 'privilege_cards', ['nfc_uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('privilege_cards', 'card_version')
    op.drop_index(op.f('ix_privilege_cards_nfc_uid'), table_name='privilege_cards')
    op.drop_column('privilege_cards', 'nfc_uid')
    op.alter_column('marketplace_listings', 'is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_card_history_user_id'), table_name='card_history')
    op.drop_index(op.f('ix_card_history_id'), table_name='card_history')
    op.drop_index(op.f('ix_card_history_card_id'), table_name='card_history')
    op.drop_table('card_history')
    # ### end Alembic commands ###
