"""add_card_history_table

Revision ID: 3a409dd0fa33
Revises: 8a9b2c3d4e5f
Create Date: 2026-05-12 09:20:58.231001
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add_card_history_table

Revision ID: 3a409dd0fa33
Revises: 8a9b2c3d4e5f
Create Date: 2026-05-12 09:20:58.231001
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a409dd0fa33'
down_revision: Union[str, None] = '8a9b2c3d4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Create card_history table if it doesn't exist
    op.execute("""
        CREATE TABLE IF NOT EXISTS card_history (
            id UUID PRIMARY KEY,
            card_id UUID NOT NULL REFERENCES privilege_cards(id) ON DELETE CASCADE,
            user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            action VARCHAR(50) NOT NULL,
            old_card_number VARCHAR(50),
            new_card_number VARCHAR(50),
            old_nfc_uid VARCHAR(100),
            new_nfc_uid VARCHAR(100),
            old_version INTEGER,
            new_version INTEGER,
            old_status VARCHAR(50),
            notes TEXT,
            performed_at TIMESTAMP WITH TIME ZONE NOT NULL,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
        )
    """)

    # 2. Create indexes if they don't exist
    op.execute("CREATE INDEX IF NOT EXISTS ix_card_history_card_id ON card_history (card_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_card_history_id ON card_history (id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_card_history_user_id ON card_history (user_id)")

    # 3. Alter marketplace_listings (wrapped in try/except or safe SQL)
    op.execute("ALTER TABLE marketplace_listings ALTER COLUMN is_approved SET NOT NULL")

    # 4. Add privilege_cards columns ONLY IF they don't exist
    op.execute("ALTER TABLE privilege_cards ADD COLUMN IF NOT EXISTS card_version INTEGER DEFAULT 1 NOT NULL")
    op.execute("ALTER TABLE privilege_cards ADD COLUMN IF NOT EXISTS nfc_uid VARCHAR(100)")
    
    # 5. Create unique index for nfc_uid if it doesn't exist
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ix_privilege_cards_nfc_uid ON privilege_cards (nfc_uid)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('privilege_cards', 'card_version')
    op.drop_index(op.f('ix_privilege_cards_nfc_uid'), table_name='privilege_cards')
    op.drop_column('privilege_cards', 'nfc_uid')
    op.alter_column('marketplace_listings', 'is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_card_history_user_id'), table_name='card_history')
    op.drop_index(op.f('ix_card_history_id'), table_name='card_history')
    op.drop_index(op.f('ix_card_history_card_id'), table_name='card_history')
    op.drop_table('card_history')
    # ### end Alembic commands ###
