"""bylaws_alignment_phase_1

Revision ID: 63c3a9c6b99a
Revises: f20e98c7d3a3
Create Date: 2026-04-30 10:46:26.937270
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63c3a9c6b99a'
down_revision: Union[str, None] = 'f20e98c7d3a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE membership_type ADD VALUE IF NOT EXISTS 'FOUNDERS_CLUB'")
    op.execute("ALTER TYPE membership_type ADD VALUE IF NOT EXISTS 'ASSOCIATE'")
    op.execute("ALTER TYPE membership_type ADD VALUE IF NOT EXISTS 'CORPORATE'")
    op.execute("CREATE TYPE verification_level AS ENUM ('NONE', 'VERIFIED', 'SILVER', 'GOLD', 'PLATINUM')")
    op.execute("CREATE TYPE designation AS ENUM ('CHAPTER_PRESIDENT', 'CHAPTER_VICE_PRESIDENT', 'CHAPTER_SECRETARY', 'CLUB_COORDINATOR', 'VP_OPERATIONS', 'VP_GROWTH', 'VP_COMMUNICATIONS', 'PLATFORM_MANAGER')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_schedules',
    sa.Column('membership_type', sa.Text(), nullable=False),
    sa.Column('annual_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('per_forum_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_schedules_id'), 'fee_schedules', ['id'], unique=False)
    op.execute("ALTER TABLE fee_schedules ALTER COLUMN membership_type TYPE membership_type USING membership_type::membership_type")
    op.create_table('horizontal_clubs',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_vertical', sa.String(length=100), nullable=False),
    sa.Column('coordinator_user_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('min_members', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coordinator_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_horizontal_clubs_id'), 'horizontal_clubs', ['id'], unique=False)
    op.create_table('horizontal_club_memberships',
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['horizontal_clubs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'user_id', name='unique_club_member')
    )
    op.create_index(op.f('ix_horizontal_club_memberships_club_id'), 'horizontal_club_memberships', ['club_id'], unique=False)
    op.create_index(op.f('ix_horizontal_club_memberships_id'), 'horizontal_club_memberships', ['id'], unique=False)
    op.create_index(op.f('ix_horizontal_club_memberships_user_id'), 'horizontal_club_memberships', ['user_id'], unique=False)
    op.create_table('user_designations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('designation', sa.String(), nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=True),
    sa.Column('club_id', sa.UUID(), nullable=True),
    sa.Column('appointed_at', sa.Date(), nullable=False),
    sa.Column('term_ends_at', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['club_id'], ['horizontal_clubs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_designations_id'), 'user_designations', ['id'], unique=False)
    op.create_index(op.f('ix_user_designations_user_id'), 'user_designations', ['user_id'], unique=False)
    op.execute("ALTER TABLE user_designations ALTER COLUMN designation TYPE designation USING designation::designation")
    op.add_column('users', sa.Column('verification_level', sa.String(), nullable=True))
    op.add_column('users', sa.Column('verification_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE users SET verification_level = 'NONE'")
    op.execute("ALTER TABLE users ALTER COLUMN verification_level TYPE verification_level USING verification_level::verification_level")
    op.execute("ALTER TABLE users ALTER COLUMN verification_level SET NOT NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_updated_at')
    op.drop_column('users', 'verification_level')
    op.drop_index(op.f('ix_user_designations_user_id'), table_name='user_designations')
    op.drop_index(op.f('ix_user_designations_id'), table_name='user_designations')
    op.drop_table('user_designations')
    op.drop_index(op.f('ix_horizontal_club_memberships_user_id'), table_name='horizontal_club_memberships')
    op.drop_index(op.f('ix_horizontal_club_memberships_id'), table_name='horizontal_club_memberships')
    op.drop_index(op.f('ix_horizontal_club_memberships_club_id'), table_name='horizontal_club_memberships')
    op.drop_table('horizontal_club_memberships')
    op.drop_index(op.f('ix_horizontal_clubs_id'), table_name='horizontal_clubs')
    op.drop_table('horizontal_clubs')
    op.drop_index(op.f('ix_fee_schedules_id'), table_name='fee_schedules')
    op.drop_table('fee_schedules')
    # ### end Alembic commands ###
