"""add_post_types_and_economic_engine_fields

Revision ID: 680978d04a4b
Revises: b24a7c5f5bf8
Create Date: 2026-04-30 13:29:18.740757
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '680978d04a4b'
down_revision: Union[str, None] = 'b24a7c5f5bf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Manual enum creation for PostgreSQL
    sa.Enum('GENERAL', 'LEAD', 'RFP', name='posttype').create(op.get_bind())
    sa.Enum('CHAPTER', 'NETWORK', 'CLUB', name='postvisibility').create(op.get_bind())
    sa.Enum('OPEN', 'IN_PROGRESS', 'CLOSED_WON', 'CLOSED_LOST', name='leadstatus').create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_posts', sa.Column('post_type', sa.Enum('GENERAL', 'LEAD', 'RFP', name='posttype'), nullable=False, server_default='GENERAL'))
    op.add_column('community_posts', sa.Column('visibility', sa.Enum('CHAPTER', 'NETWORK', 'CLUB', name='postvisibility'), nullable=False, server_default='CHAPTER'))
    op.add_column('community_posts', sa.Column('lead_status', sa.Enum('OPEN', 'IN_PROGRESS', 'CLOSED_WON', 'CLOSED_LOST', name='leadstatus'), nullable=True))
    op.add_column('community_posts', sa.Column('target_club_id', sa.UUID(), nullable=True))
    op.add_column('community_posts', sa.Column('target_industry_id', sa.UUID(), nullable=True))
    op.add_column('community_posts', sa.Column('budget_range', sa.String(length=100), nullable=True))
    op.add_column('community_posts', sa.Column('deadline', sa.DateTime(), nullable=True))
    op.add_column('community_posts', sa.Column('business_value', sa.Numeric(precision=15, scale=2), nullable=True))
    op.create_index(op.f('ix_community_posts_lead_status'), 'community_posts', ['lead_status'], unique=False)
    op.create_index(op.f('ix_community_posts_post_type'), 'community_posts', ['post_type'], unique=False)
    op.create_index(op.f('ix_community_posts_visibility'), 'community_posts', ['visibility'], unique=False)
    op.create_foreign_key(None, 'community_posts', 'horizontal_clubs', ['target_club_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'community_posts', 'industry_categories', ['target_industry_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'community_posts', type_='foreignkey')
    op.drop_constraint(None, 'community_posts', type_='foreignkey')
    op.drop_index(op.f('ix_community_posts_visibility'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_post_type'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_lead_status'), table_name='community_posts')
    op.drop_column('community_posts', 'business_value')
    op.drop_column('community_posts', 'deadline')
    op.drop_column('community_posts', 'budget_range')
    op.drop_column('community_posts', 'target_industry_id')
    op.drop_column('community_posts', 'target_club_id')
    op.drop_column('community_posts', 'lead_status')
    op.drop_column('community_posts', 'visibility')
    op.drop_column('community_posts', 'post_type')
    # ### end Alembic commands ###

    # Manual enum removal
    sa.Enum(name='posttype').drop(op.get_bind())
    sa.Enum(name='postvisibility').drop(op.get_bind())
    sa.Enum(name='leadstatus').drop(op.get_bind())
