"""add_partner_admin_role

Revision ID: 7dca487aaf51
Revises: 15e5eca89ac6
Create Date: 2026-04-06 17:21:18.399440
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dca487aaf51'
down_revision: Union[str, None] = '15e5eca89ac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'PARTNER_ADMIN'")
    op.add_column('partners', sa.Column('admin_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_partners_admin_id'), 'partners', ['admin_id'], unique=False)
    op.create_foreign_key(None, 'partners', 'users', ['admin_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'partners', type_='foreignkey')
    op.drop_index(op.f('ix_partners_admin_id'), table_name='partners')
    op.drop_column('partners', 'admin_id')
    # ### end Alembic commands ###
