"""add_embedding_columns

Revision ID: b2641d403673
Revises: a49fb2318d75
Create Date: 2026-07-02 03:44:32.574774
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2641d403673'
down_revision: Union[str, None] = 'a49fb2318d75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matching_profiles', sa.Column('services_embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('matching_profiles', sa.Column('looking_for_embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matching_profiles', 'looking_for_embedding')
    op.drop_column('matching_profiles', 'services_embedding')
    # ### end Alembic commands ###
