"""add payment proofs table

Revision ID: be7d8d8619a2
Revises: 8a9b2c3d4e60
Create Date: 2026-06-23 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'be7d8d8619a2'
down_revision = '8a9b2c3d4e60'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_proofs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('proof_type', postgresql.ENUM('image', 'pdf', 'reference_number', name='payment_proof_type', create_type=False), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('reference_number', sa.String(length=255), nullable=True),
    sa.Column('upload_token', sa.String(length=255), nullable=False),
    sa.Column('upload_token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', postgresql.ENUM('pending_review', 'approved', 'rejected', name='payment_proof_status', create_type=False), nullable=False),
    sa.Column('admin_notes', sa.String(length=1000), nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_proofs_id'), 'payment_proofs', ['id'], unique=False)
    op.create_index(op.f('ix_payment_proofs_payment_id'), 'payment_proofs', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payment_proofs_upload_token'), 'payment_proofs', ['upload_token'], unique=True)
    op.create_index(op.f('ix_payment_proofs_user_id'), 'payment_proofs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_proofs_user_id'), table_name='payment_proofs')
    op.drop_index(op.f('ix_payment_proofs_upload_token'), table_name='payment_proofs')
    op.drop_index(op.f('ix_payment_proofs_payment_id'), table_name='payment_proofs')
    op.drop_index(op.f('ix_payment_proofs_id'), table_name='payment_proofs')
    op.drop_table('payment_proofs')
    # ### end Alembic commands ###
