"""add marketplace tables

Revision ID: e870291fa9b9
Revises: 680978d04a4b
Create Date: 2026-04-30 16:49:47.425506
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e870291fa9b9'
down_revision: Union[str, None] = '680978d04a4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_listings',
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('PRODUCT', 'SERVICE', 'CONSULTATION', name='listingcategory'), nullable=False),
    sa.Column('industry_category_id', sa.UUID(), nullable=False),
    sa.Column('regular_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('member_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('price_note', sa.String(length=100), nullable=True),
    sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'SOLD_OUT', 'FLAGGED', 'REMOVED', name='listingstatus'), nullable=False),
    sa.Column('whatsapp_number', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('interest_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['industry_category_id'], ['industry_categories.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_listings_category'), 'marketplace_listings', ['category'], unique=False)
    op.create_index(op.f('ix_marketplace_listings_id'), 'marketplace_listings', ['id'], unique=False)
    op.create_index(op.f('ix_marketplace_listings_industry_category_id'), 'marketplace_listings', ['industry_category_id'], unique=False)
    op.create_index(op.f('ix_marketplace_listings_seller_id'), 'marketplace_listings', ['seller_id'], unique=False)
    op.create_index(op.f('ix_marketplace_listings_status'), 'marketplace_listings', ['status'], unique=False)
    op.create_table('marketplace_interests',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('interested_user_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interested_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['marketplace_listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'interested_user_id', name='unique_member_interest')
    )
    op.create_index(op.f('ix_marketplace_interests_id'), 'marketplace_interests', ['id'], unique=False)
    op.create_index(op.f('ix_marketplace_interests_interested_user_id'), 'marketplace_interests', ['interested_user_id'], unique=False)
    op.create_index(op.f('ix_marketplace_interests_listing_id'), 'marketplace_interests', ['listing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketplace_interests_listing_id'), table_name='marketplace_interests')
    op.drop_index(op.f('ix_marketplace_interests_interested_user_id'), table_name='marketplace_interests')
    op.drop_index(op.f('ix_marketplace_interests_id'), table_name='marketplace_interests')
    op.drop_table('marketplace_interests')
    op.drop_index(op.f('ix_marketplace_listings_status'), table_name='marketplace_listings')
    op.drop_index(op.f('ix_marketplace_listings_seller_id'), table_name='marketplace_listings')
    op.drop_index(op.f('ix_marketplace_listings_industry_category_id'), table_name='marketplace_listings')
    op.drop_index(op.f('ix_marketplace_listings_id'), table_name='marketplace_listings')
    op.drop_index(op.f('ix_marketplace_listings_category'), table_name='marketplace_listings')
    op.drop_table('marketplace_listings')
    # ### end Alembic commands ###
