"""add_cumulative_value_to_user

Revision ID: ecbc08826376
Revises: 63c3a9c6b99a
Create Date: 2026-04-30 10:52:46.872988
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecbc08826376'
down_revision: Union[str, None] = '63c3a9c6b99a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cumulative_value_generated', sa.Numeric(precision=16, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cumulative_value_generated')
    # ### end Alembic commands ###
