"""add_redemption_method_to_offer

Revision ID: f03cfac30799
Revises: 4ac1fa336316
Create Date: 2026-04-10 15:25:42.860218
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f03cfac30799'
down_revision: Union[str, None] = '4ac1fa336316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('redemption_method', sa.Enum('QR', 'COUPON', name='redemption_method'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'redemption_method')
    # ### end Alembic commands ###
